// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtX-qGgP1JPOceeStEeaQ_fCsdPZ9Tw9g',
    appId: '1:743578028103:web:b860ae8c14d8f5c8d14962',
    messagingSenderId: '743578028103',
    projectId: 'chatapp-4f15b',
    authDomain: 'chatapp-4f15b.firebaseapp.com',
    storageBucket: 'chatapp-4f15b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpAKvD14aDQE3RKopwTQjoefuwykdjBAw',
    appId: '1:743578028103:android:5259e9c383d5a2cbd14962',
    messagingSenderId: '743578028103',
    projectId: 'chatapp-4f15b',
    storageBucket: 'chatapp-4f15b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqDL6f2plG82_FISF9q43O3oVOTAzY23E',
    appId: '1:743578028103:ios:27f6b1bbf60a2f82d14962',
    messagingSenderId: '743578028103',
    projectId: 'chatapp-4f15b',
    storageBucket: 'chatapp-4f15b.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqDL6f2plG82_FISF9q43O3oVOTAzY23E',
    appId: '1:743578028103:ios:27f6b1bbf60a2f82d14962',
    messagingSenderId: '743578028103',
    projectId: 'chatapp-4f15b',
    storageBucket: 'chatapp-4f15b.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );
}
